#! /bin/bash
set -e
LOG="${LOG-pio_write.log}"
if [ yes != yes ]; then
  # skip tests for unsupported formats
  exit 77
fi
mpi_task_num="${mpi_task_num-4}"
suffix="${suffix-grb}"
if [ "" = yes ]; then
  variations="-qcache-redists"
else
  unset variations
fi
for variation in "" $variations ; do
  exec 5>&1 6>&2 >"$LOG" 2>&1
  ../libtool --mode=execute \
    /opt/render/project/src/child-processes/cdo/cdo-1.9.1/libcdi/util/serialrun \
    -n ${mpi_task_num} ${tool_wrap} ./pio_write ${pio_write_args} ${variation}
  exec 2>&6 1>&5 5>&- 6>&-
  ../libtool --mode=execute \
    ${tool_wrap} ./cksum_read example_0.${suffix} example_0.cksum
  ../libtool --mode=execute \
    ${tool_wrap} ./cksum_read example_1.${suffix} example_1.cksum
  \rm "$LOG"
done
#
# Local Variables:
# mode: sh
# End:
#
