#! /bin/bash
set -e
mpi_task_num="${mpi_task_num-1}"
../libtool --mode=execute /opt/render/project/src/child-processes/cdo/cdo-1.9.1/libcdi/util/serialrun -n ${mpi_task_num} \
  ./test_resource_copy_mpi
